# Generated by Django 3.2.8 on 2022-06-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('category', models.CharField(choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('FS', 'Fullstack')], default='FE', max_length=3)),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PUB', 'Published')], default='DR', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Gönderiler',
                'ordering': ['category'],
            },
        ),
    ]
